export const CAR_MODELS: Record<string, string[]> = {
    "טויוטה": ["קורולה", "יאריס", "CHR", "C-HR", "RAV4", "לנד קרוזר", "פריוס", "אייגו", "קאמרי", "היילקס", "ורסו", "אויונסיס", "קורולה קרוס", "Corolla", "Yaris", "Land Cruiser", "Prius", "Aygo", "Camry", "Hilux", "Verso", "Avensis", "bz4x", "Proace", "Sienna", "סיינה", "פרואייס", "Supra", "סופרה", "GT86"],
    "יונדאי": ["i10", "i20", "i25", "i30", "i35", "אלנטרה", "איוניק", "טוסון", "סנטה פה", "קונה", "סונטה", "וניו", "באיון", "Elantra", "Ioniq", "Tucson", "Santa Fe", "Kona", "Sonata", "Venue", "Bayon", "Getz", "גטס", "אקסנט", "Accent", "i30N", "Veloster", "ולוסטר", "Matrix", "מטריקס", "ix35", "Ioniq 5", "Ioniq 6", "Staria", "סטאריה", "Palisade", "פליסייד"],
    "קיה": ["פיקנטו", "ריו", "פורטה", "סיד", "ספורטאז'", "סורנטו", "נירו", "סטוניק", "קרניבל", "סלטוס", "Picanto", "Rio", "Forte", "Ceed", "Sportage", "Sorento", "Niro", "Stonic", "Carnival", "Seltos", "EV6", "EV9", "ProCeed", "פרו סיד", "Xceed", "אקסיד", "Carens", "קארנס", "Soul", "סול", "Optima", "אופטימה"],
    "מזדה": ["2", "3", "6", "CX3", "CX-3", "CX30", "CX-30", "CX5", "CX-5", "CX9", "CX-9", "לאנטיס", "Lantis", "Demio", "MX-5", "CX-60", "CX-90", "BT-50"],
    "סקודה": ["פאביה", "אוקטביה", "סופרב", "קודיאק", "קארוק", "קאמיק", "סקאלה", "Fabia", "Octavia", "Superb", "Kodiaq", "Karoq", "Kamiq", "Scala", "Yeti", "ייטי", "Enyaq", "אניאק", "Citigo", "סיטיגו", "Rapid", "ראפיד", "Roomster", "רומסטר"],
    "סיאט": ["איביזה", "לאון", "ארונה", "אטקה", "טראקו", "Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Mii", "מי", "Toledo", "טולדו", "Altea", "אלתאה"],
    "פולקסווגן": ["פולו", "גולף", "פאסאט", "טיגואן", "טוארג", "ג'טה", "טי-רוק", "טי-קרוס", "Polo", "Golf", "Passat", "Tiguan", "Touareg", "Jetta", "T-Roc", "T-Cross", "ID.3", "ID.4", "ID.5", "ID.Buzz", "Arteon", "ארטאון", "Scirocco", "שירוקו", "Beetle", "חיפושית", "Touran", "טוראן", "Caddy", "קאדי", "Amarok", "אמרוק", "Multivan", "מולטיואן", "Transporter", "טרנספורטר", "Caravelle", "קראוול"],
    "שברולט": ["ספארק", "קרוז", "מאליבו", "טראקס", "אקווינוקס", "טראוורס", "Spark", "Cruze", "Malibu", "Trax", "Equinox", "Traverse", "Tahoe", "טאהו", "Suburban", "סברבן", "Silverado", "סילברדו", "Colorado", "קולורדו", "Camaro", "קאמרו", "Corvette", "קורבט", "Impala", "אימפלה", "Sonic", "סוניק", "Aveo", "אבאו", "Captiva", "קפטיבה", "Orlando", "אורלנדו", "Blazer", "בלייזר", "Trailblazer", "טריילבלייזר"],
    "סוזוקי": ["סוויפט", "איגניס", "בלנו", "ויטרה", "קרוסאובר", "ג'ימני", "אלטו", "ספלש", "Swift", "Ignis", "Baleno", "Vitara", "SX4", "Crossover", "Jimny", "Alto", "Splash", "Grand Vitara", "גרנד ויטרה", "Celerio", "סלריו", "S-Cross", "Swace", "Across"],
    "הונדה": ["ג'אז", "סיוויק", "אקורד", "HRV", "CRV", "Jazz", "Civic", "Accord", "HR-V", "CR-V", "ZR-V", "Insight", "אינסייט", "Pilot", "פיילוט", "Odyssey", "אודיסי", "S2000", "Legend", "לג'נד", "FR-V"],
    "מיצובישי": ["ספייס סטאר", "לאנסר", "ASX", "אקליפס", "אאוטלנדר", "Space Star", "Lancer", "Eclipse Cross", "Outlander", "Pajero", "פאג'רו", "Triton", "טרייטון", "Hunter", "האנטר", "Grandis", "גרנדיס", "Colt", "קולט", "Attrage", "אטראז'"],
    "ניסן": ["מיקרה", "ג'וק", "קשקאי", "אקסטרייל", "סנטרה", "Micra", "Juke", "Qashqai", "X-Trail", "Sentra", "Altima", "אלטימה", "Maxima", "מקסימה", "Leaf", "ליף", "Ariya", "Navara", "נבארה", "Note", "נוט", "Tiida", "טידה", "Murano", "מוראנו", "Pathfinder", "פאת'פיינדר", "Patrol", "פטרול", "GT-R", "370Z"],
    "פיג'ו": ["208", "3008", "5008", "2008", "308", "107", "108", "206", "207", "301", "307", "407", "408", "508", "Partner", "פרטנר", "Rifter", "ריפטר", "Traveller", "טראבלר", "Boxer", "בוקסר", "RCZ"],
    "רנו": ["קליאו", "מגאן", "קפצ'ור", "קדג'אר", "גרנד סניק", "Clio", "Megane", "Captur", "Kadjar", "Grand Scenic", "Arkana", "ארקנה", "Austral", "אוסטרל", "Koleos", "קולאוס", "Zoe", "זואי", "Twingo", "טווינגו", "Fluence", "פלואנס", "Kangoo", "קנגו", "Traffic", "טראפיק", "Master", "מאסטר"],
    "סיטרואן": ["C3", "C4", "C5", "ברלינגו", "Berlingo", "C1", "C3 Aircross", "C4 X", "C5 Aircross", "C5 X", "Jumpy", "ג'אמפי", "C-Elysee", "אליזה", "C4 Picasso", "פיקאסו", "Cactus", "קקטוס"],
    "סובארו": ["אימפרזה", "XV", "פורסטר", "אאוטבק", "B4", "Impreza", "Forester", "Outback", "Crosstrek", "קרוסטראק", "Evoltis", "אבולטיס", "BRZ", "Levorg", "לבורג", "Tribeca", "טריבקה"],
    "אאודי": ["A1", "A3", "A4", "A5", "A6", "Q2", "Q3", "Q5", "Q7", "Q8", "e-tron", "אי-טרון", "A7", "A8", "TT", "R8", "Q4", "RS3", "RSQ3", "S3", "Q5 Sportback", "Q3 Sportback"],
    "BMW": ["סדרה 1", "סדרה 3", "סדרה 5", "X1", "X3", "X5", "X6", "1 Series", "3 Series", "5 Series", "X2", "X4", "X7", "XM", "7 Series", "סדרה 7", "4 Series", "סדרה 4", "2 Series", "סדרה 2", "iX", "i4", "iX3", "iX1", "i7", "i5", "Z4", "M2", "M3", "M4", "M5"],
    "מרצדס": ["A-Class", "C-Class", "E-Class", "S-Class", "CLA", "GLA", "GLC", "GLE", "EQA", "EQB", "EQC", "EQE", "EQS", "V-Class", "Sprinter", "ספרינטר", "Vito", "ויטו", "G-Class", "GLB", "GLS", "CLS", "SL", "AMG GT"],
    "טסלה": ["מודל 3", "מודל Y", "מודל S", "מודל X", "Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
    "BYD": ["אטו 3", "Atto 3", "האן", "Han", "טאנג", "Tang", "דולפין", "Dolphin", "Seal", "סיל"],
    "ג'ילי": ["גיאומטרי C", "Geometry C"],
    "צ'רי": ["טיגו 8", "Tiggo 8", "FX", "Tiggo 7", "טיגו 7", "Omoda", "אומודה"],
    "וולוו": ["XC40", "XC60", "XC90", "S60", "S90", "V60", "V90", "C40", "EX30", "EX90", "V40"],
    "לנד רובר": ["דיסקברי", "דיסקברי ספורט", "ריינג' רובר", "איווק", "ולאר", "ספורט", "דיפנדר", "Discovery", "Range Rover", "Evoque", "Velar", "Defender"],
    "לקסוס": ["UX", "NX", "RX", "ES", "LS", "IS", "CT", "GS", "RZ", "LBX", "GX", "LX", "LC", "RC"],
    "אינפיניטי": ["Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX55", "QX60", "QX70", "QX80"],
    "קאדילק": ["CT4", "CT5", "CT6", "XT4", "XT5", "XT6", "Escalade", "אסקלייד", "Lyriq", "ליריק", "ATS", "CTS", "SRX"],
    "ג'יפ": ["רנגלר", "גרנד צ'ירוקי", "צ'ירוקי", "קומפאס", "רנגייד", "גלדיאטור", "Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Renegade", "Gladiator", "Avenger", "אוונג'ר"],
    "דאצ'יה": ["דאסטר", "סנדרו", "ג'וגר", "לוגאן", "לודג'י", "Duster", "Sandero", "Jogger", "Logan", "Lodgy", "Spring", "ספרינג"],
    "פיאט": ["500", "500X", "500e", "פנדה", "Panda", "טיפו", "Tipo", "דובלו", "Doblo", "דוקאטו", "Ducato", "פונטו", "Punto", "בראבו", "Bravo"],
    "פורד": ["פוקוס", "פיאסטה", "מונדאו", "קוגה", "אדג'", "אקספלורר", "ברונקו", "Focus", "Fiesta", "Mondeo", "Kuga", "Edge", "Explorer", "Bronco", "Mustang", "מוסטנג", "F-150", "F-350", "Puma", "פומה", "Ranger", "ריינג'ר", "Transit", "טרנזיט"],
    "אופל": ["קורסה", "אסטרה", "מוקה", "קרוסלנד", "גרנדלנד", "אינסיגניה", "Corsa", "Astra", "Mokka", "Crossland", "Grandland", "Insignia", "Adam", "אדם", "Zafira", "זאפירה", "Meriva", "מריבה"],
    "מיני": ["קופר", "Countryman", "קאנטרימן", "Clubman", "קלאבמן", "One", "וואן", "Cooper"],
    "סמארט": ["Fortwo", "Forfour", "#1", "#3"],
    "אלפא רומיאו": ["ג'ולייטה", "מיטו", "ג'וליה", "סטלביו", "Giulietta", "MiTo", "Giulia", "Stelvio", "Tonale", "טונאלה"],
    "MG": ["ZS", "EHS", "Marvel R", "MG4", "MG5", "Cyberster", "MG3"],
    "איווייס": ["U5", "U6"],
    "סקיוול": ["ET5"],
    "סרס": ["3", "5"],
    "מקסוס": ["Euniq 5", "Euniq 6", "Deliver 9"],
    "ליפמוטור": ["T03", "C11"],
    "וויה": ["Free", "Dream"],
    "זיקר": ["001", "X"],
    "אקספנג": ["P7", "G9"],
    "ניו": ["ET5", "ET7", "EL7", "ES8"],
    "פורשה": ["911", "בוקסטר", "קיימן", "קאיין", "מקאן", "פנמרה", "טייקאן", "Boxster", "Cayman", "Cayenne", "Macan", "Panamera", "Taycan"],
    "מזראטי": ["גיבלי", "לבנטה", "גרקאלה", "Ghibli", "Levante", "Grecale", "Quattroporte", "קוואטרופורטה", "GranTurismo", "גרנרטוריסמו"],
    "יגואר": ["XE", "XF", "XJ", "E-Pace", "F-Pace", "I-Pace", "F-Type"],
    "איסוזו": ["D-Max", "Sumo", "טרופר", "Trooper", "רודאו", "Rodeo"],
    "סאנגיונג": ["רקסטון", "קוראנדו", "טיבולי", "מוסו", "Rexton", "Korando", "Tivoli", "Musso", "טורס", "Torres"]
};
